version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse_net

  spark:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8088:8080"
      - "7077:7077"
    volumes:
      - ./spark:/opt/spark-apps
    networks:
      - lakehouse_net

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    user: "50000:0"
    depends_on:
      - minio
      - spark
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8080:8080"
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db init &&
      airflow users create
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com || true &&
      airflow webserver & airflow scheduler"
    networks:
      - lakehouse_net


  # duckdb:
  #   image: python:3.10-slim
  #   container_name: duckdb
  #   volumes:
  #     - ./duckdb:/app
  #   working_dir: /app
  #   command: tail -f /dev/null
  #   networks:
  #     - lakehouse_net

  # superset:
  #   image: apache/superset:latest
  #   container_name: superset
  #   depends_on:
  #     - duckdb
  #   ports:
  #     - "8089:8088"
  #   environment:
  #     SUPERSET_SECRET_KEY: supersecretkey
  #   volumes:
  #     - superset_home:/app/superset_home
  #   command: >
  #     bash -c "
  #     superset db upgrade &&
  #     superset fab create-admin
  #       --username admin
  #       --firstname Admin
  #       --lastname User
  #       --email admin@example.com
  #       --password admin &&
  #     superset init &&
  #     superset run -h 0.0.0.0 -p 8088"
  #   networks:
  #     - lakehouse_net

volumes:
  minio_data:
  airflow_dags:
  airflow_logs:
  airflow_plugins:
  # superset_home:

networks:
  lakehouse_net:
    driver: bridge
